services:
  # web:
    # build: 
      # context: CatalogService
      # dockerfile: Web/Dockerfile
    # ports:
      # - 43320:8080
  # identity:
    # build: 
      # context: Identity
      # dockerfile: src/IdentityServerAspNetIdentity/Dockerfile
    # ports:
      # - 5001:8080
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  db:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: example_123
    image: mcr.microsoft.com/mssql/server
    ports:
       - 1433:1433
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
    volumes:
        - ./data:/var/opt/mssql/data